// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSVoOO51JezLBvMtlKSJq6CPxyUr9aT_s',
    appId: '1:558131561267:web:0ac896e5fff1dd719b3446',
    messagingSenderId: '558131561267',
    projectId: 'bus-tracking-system-65440',
    authDomain: 'bus-tracking-system-65440.firebaseapp.com',
    storageBucket: 'bus-tracking-system-65440.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLfOzb_khpXlfCYLqQp-ednOAkdUzZ90',
    appId: '1:558131561267:android:82fb536f674bc8599b3446',
    messagingSenderId: '558131561267',
    projectId: 'bus-tracking-system-65440',
    storageBucket: 'bus-tracking-system-65440.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0LoBl3LoQ79Gwd7rdhbyIqlTv47ddrjc',
    appId: '1:558131561267:ios:78e790737a01464b9b3446',
    messagingSenderId: '558131561267',
    projectId: 'bus-tracking-system-65440',
    storageBucket: 'bus-tracking-system-65440.firebasestorage.app',
    iosBundleId: 'com.example.busTrackingManagementSystem',
  );
}
